//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRentalApplication.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.RentedMovies = new HashSet<RentedMovie>();
        }
        [DisplayName("User ID")]
        public int userID { get; set; }
        [DisplayName("User Full Name")]
        [Required]
        [StringLength(20,ErrorMessage = "Name should be 20 chars long")]
        public string name { get; set; }
        [DisplayName("Credit Card")]
        [Required]
        [RegularExpression(@"^\d{16}$",ErrorMessage = "Credit Card number should be 16 digits.")]
        public string creditcard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentedMovie> RentedMovies { get; set; }
    }
}
